//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.19 at 02:19:55 PM CAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kwizera.rw/springsoapexample", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rw.kwizera.springsoapexample;
